#!/bin/sh

### BEGIN INIT INFO
# Provides:          echessd
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Internet Chess Server
# Description: Echessd is an lightweight and minimalistic
#    Internet Chess Server written with the Erlang programming language.
### END INIT INFO

# Author: Aleksey Morarash <aleksey.morarash@gmail.com>

PATH=/sbin:/bin:/usr/bin
DESC="Internet Chess Server"
NAME=echessd
DAEMON=/usr/bin/${NAME}-wrapper
CONFIG="/etc/echessd.conf"
PIDFILE=/var/lib/$NAME/pid
SCRIPTNAME=/etc/init.d/$NAME

# Exit if the package is not installed
[ -x "$DAEMON" ] || exit 0

# Read configuration variable file if it is present
[ -r /etc/default/$NAME ] && . /etc/default/$NAME

# Load the VERBOSE setting and other rcS variables
. /lib/init/vars.sh

# Define LSB log_* functions.
# Depend on lsb-base (>= 3.2-14) to ensure that this file is present
# and status_of_proc is working.
. /lib/lsb/init-functions

#
# Function that starts the daemon/service
#
do_start() {
    # Return
    #   0 if daemon has been started
    #   1 if daemon was already running
    #   2 if daemon could not be started
    $DAEMON --ping $CONFIG > /dev/null && return 1
    do_fix_cookie_permissions
    start-stop-daemon --quiet --start --background --make-pidfile \
        --pidfile $PIDFILE --user $NAME --chuid $NAME \
        --exec $DAEMON -- $CONFIG || return 2
}

#
# Function that stops the daemon/service
#
do_stop() {
    # Return
    #   0 if daemon has been stopped
    #   1 if daemon was already stopped
    #   2 if daemon could not be stopped
    #   other if a failure occurred
    $DAEMON --stop $CONFIG 2> /dev/null
    RETVAL="$?"
    do_fix_cookie_permissions
    [ "$RETVAL" = 2 ] && return 2
    rm -f $PIDFILE
    return "$RETVAL"
}

#
# Fix permissions of Erlang distribution cookie file
#
do_fix_cookie_permissions() {
    [ -f /var/lib/$NAME/.erlang.cookie ] && \
        chown $NAME: /var/lib/$NAME/.erlang.cookie
}

case "$1" in
    start)
        [ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC" "$NAME"
        do_start
        case "$?" in
            0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
            2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
        esac
        ;;
    stop)
        [ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC" "$NAME"
        do_stop
        case "$?" in
            0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
            2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
        esac
        ;;
    status)
        $DAEMON --ping $CONFIG > /dev/null
        RETVAL="$?"
        do_fix_cookie_permissions
        if [ "$VERBOSE" != no ]; then
            case "$RETVAL" in
                0) log_success_msg "$DESC $NAME is running" ;;
                1) log_failure_msg "$DESC $NAME is not running" ;;
            esac
        fi
        exit $RETVAL
        ;;
    reload|force-reload)
        log_daemon_msg "Reloading $DESC" "$NAME"
        $DAEMON --hup $CONFIG
        log_end_msg $?
        do_fix_cookie_permissions
        ;;
    restart)
        log_daemon_msg "Restarting $DESC" "$NAME"
        do_stop
        case "$?" in
            0|1)
                do_start
                case "$?" in
                    0) log_end_msg 0 ;;
                    1) log_end_msg 1 ;; # Old process is still running
                    *) log_end_msg 1 ;; # Failed to start
                esac
                ;;
            *) log_end_msg 1 ;; # Failed to stop
        esac
        ;;
    *)
        echo "Usage: $SCRIPTNAME {start|stop|status|restart|reload}" >&2
        exit 3
        ;;
esac

:
